# Generated by Django 3.2 on 2024-10-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAutores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
